language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: cp .travis.oasis _oasis && bash -ex .travis-opam.sh && bash -ex .coveralls.sh
env:
  - OCAML_VERSION=4.02 PACKAGE=mirage-block-volume EXTRA_REMOTES=git://github.com/xapi-project/thin-lvhd-opam-repo
